/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVentesRouteImport } from './routes/_authenticated/ventes'
import { Route as AuthenticatedTachesRouteImport } from './routes/_authenticated/taches'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedQualiteRouteImport } from './routes/_authenticated/qualite'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedHistoriqueRouteImport } from './routes/_authenticated/historique'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated/finances'
import { Route as AuthenticatedDebloquerRouteImport } from './routes/_authenticated/debloquer'
import { Route as AuthenticatedCorbeilleRouteImport } from './routes/_authenticated/corbeille'
import { Route as AuthenticatedAujourdhuiRouteImport } from './routes/_authenticated/aujourdhui'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProduitNouveauRouteImport } from './routes/_authenticated/produit.nouveau'
import { Route as AuthenticatedProduitIdRouteImport } from './routes/_authenticated/produit.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVentesRoute = AuthenticatedVentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTachesRoute = AuthenticatedTachesRouteImport.update({
  id: '/taches',
  path: '/taches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQualiteRoute = AuthenticatedQualiteRouteImport.update({
  id: '/qualite',
  path: '/qualite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoriqueRoute = AuthenticatedHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDebloquerRoute = AuthenticatedDebloquerRouteImport.update({
  id: '/debloquer',
  path: '/debloquer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCorbeilleRoute = AuthenticatedCorbeilleRouteImport.update({
  id: '/corbeille',
  path: '/corbeille',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAujourdhuiRoute = AuthenticatedAujourdhuiRouteImport.update({
  id: '/aujourdhui',
  path: '/aujourdhui',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProduitNouveauRoute =
  AuthenticatedProduitNouveauRouteImport.update({
    id: '/produit/nouveau',
    path: '/produit/nouveau',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProduitIdRoute = AuthenticatedProduitIdRouteImport.update({
  id: '/produit/$id',
  path: '/produit/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/aujourdhui': typeof AuthenticatedAujourdhuiRoute
  '/corbeille': typeof AuthenticatedCorbeilleRoute
  '/debloquer': typeof AuthenticatedDebloquerRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/qualite': typeof AuthenticatedQualiteRoute
  '/stock': typeof AuthenticatedStockRoute
  '/taches': typeof AuthenticatedTachesRoute
  '/ventes': typeof AuthenticatedVentesRoute
  '/produit/$id': typeof AuthenticatedProduitIdRoute
  '/produit/nouveau': typeof AuthenticatedProduitNouveauRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/aujourdhui': typeof AuthenticatedAujourdhuiRoute
  '/corbeille': typeof AuthenticatedCorbeilleRoute
  '/debloquer': typeof AuthenticatedDebloquerRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/qualite': typeof AuthenticatedQualiteRoute
  '/stock': typeof AuthenticatedStockRoute
  '/taches': typeof AuthenticatedTachesRoute
  '/ventes': typeof AuthenticatedVentesRoute
  '/produit/$id': typeof AuthenticatedProduitIdRoute
  '/produit/nouveau': typeof AuthenticatedProduitNouveauRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/aujourdhui': typeof AuthenticatedAujourdhuiRoute
  '/_authenticated/corbeille': typeof AuthenticatedCorbeilleRoute
  '/_authenticated/debloquer': typeof AuthenticatedDebloquerRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/historique': typeof AuthenticatedHistoriqueRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/qualite': typeof AuthenticatedQualiteRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/taches': typeof AuthenticatedTachesRoute
  '/_authenticated/ventes': typeof AuthenticatedVentesRoute
  '/_authenticated/produit/$id': typeof AuthenticatedProduitIdRoute
  '/_authenticated/produit/nouveau': typeof AuthenticatedProduitNouveauRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/aujourdhui'
    | '/corbeille'
    | '/debloquer'
    | '/finances'
    | '/historique'
    | '/kanban'
    | '/qualite'
    | '/stock'
    | '/taches'
    | '/ventes'
    | '/produit/$id'
    | '/produit/nouveau'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/aujourdhui'
    | '/corbeille'
    | '/debloquer'
    | '/finances'
    | '/historique'
    | '/kanban'
    | '/qualite'
    | '/stock'
    | '/taches'
    | '/ventes'
    | '/produit/$id'
    | '/produit/nouveau'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/aujourdhui'
    | '/_authenticated/corbeille'
    | '/_authenticated/debloquer'
    | '/_authenticated/finances'
    | '/_authenticated/historique'
    | '/_authenticated/kanban'
    | '/_authenticated/qualite'
    | '/_authenticated/stock'
    | '/_authenticated/taches'
    | '/_authenticated/ventes'
    | '/_authenticated/produit/$id'
    | '/_authenticated/produit/nouveau'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ventes': {
      id: '/_authenticated/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof AuthenticatedVentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taches': {
      id: '/_authenticated/taches'
      path: '/taches'
      fullPath: '/taches'
      preLoaderRoute: typeof AuthenticatedTachesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qualite': {
      id: '/_authenticated/qualite'
      path: '/qualite'
      fullPath: '/qualite'
      preLoaderRoute: typeof AuthenticatedQualiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historique': {
      id: '/_authenticated/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AuthenticatedHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debloquer': {
      id: '/_authenticated/debloquer'
      path: '/debloquer'
      fullPath: '/debloquer'
      preLoaderRoute: typeof AuthenticatedDebloquerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corbeille': {
      id: '/_authenticated/corbeille'
      path: '/corbeille'
      fullPath: '/corbeille'
      preLoaderRoute: typeof AuthenticatedCorbeilleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aujourdhui': {
      id: '/_authenticated/aujourdhui'
      path: '/aujourdhui'
      fullPath: '/aujourdhui'
      preLoaderRoute: typeof AuthenticatedAujourdhuiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produit/nouveau': {
      id: '/_authenticated/produit/nouveau'
      path: '/produit/nouveau'
      fullPath: '/produit/nouveau'
      preLoaderRoute: typeof AuthenticatedProduitNouveauRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produit/$id': {
      id: '/_authenticated/produit/$id'
      path: '/produit/$id'
      fullPath: '/produit/$id'
      preLoaderRoute: typeof AuthenticatedProduitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAujourdhuiRoute: typeof AuthenticatedAujourdhuiRoute
  AuthenticatedCorbeilleRoute: typeof AuthenticatedCorbeilleRoute
  AuthenticatedDebloquerRoute: typeof AuthenticatedDebloquerRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedHistoriqueRoute: typeof AuthenticatedHistoriqueRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedQualiteRoute: typeof AuthenticatedQualiteRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedTachesRoute: typeof AuthenticatedTachesRoute
  AuthenticatedVentesRoute: typeof AuthenticatedVentesRoute
  AuthenticatedProduitIdRoute: typeof AuthenticatedProduitIdRoute
  AuthenticatedProduitNouveauRoute: typeof AuthenticatedProduitNouveauRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAujourdhuiRoute: AuthenticatedAujourdhuiRoute,
  AuthenticatedCorbeilleRoute: AuthenticatedCorbeilleRoute,
  AuthenticatedDebloquerRoute: AuthenticatedDebloquerRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedHistoriqueRoute: AuthenticatedHistoriqueRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedQualiteRoute: AuthenticatedQualiteRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedTachesRoute: AuthenticatedTachesRoute,
  AuthenticatedVentesRoute: AuthenticatedVentesRoute,
  AuthenticatedProduitIdRoute: AuthenticatedProduitIdRoute,
  AuthenticatedProduitNouveauRoute: AuthenticatedProduitNouveauRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
